language: node_js
services:
  - docker
  - mysql
  - redis

cache:
  yarn: true

addons:
  ssh_known_hosts: 47.75.127.82

before_install:
  - openssl aes-256-cbc -K $encrypted_629bc493d5be_key -iv $encrypted_629bc493d5be_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - export PATH="/home/travis/.deno/bin:$PATH"

script:
  - export DENO_DIR="$PWD/cache"
  - deno fetch -c tsconfig.json ./server.ts
  - deno run -A -c tsconfig.json ./test.ts
  - docker build ./ -t registry.cn-hongkong.aliyuncs.com/denocn/denocn-api
  - docker login -u $DOCKER_USER -p $DOCKER_PASS registry.cn-hongkong.aliyuncs.com
  - docker push registry.cn-hongkong.aliyuncs.com/denocn/denocn-api

after_success:
  - ssh root@47.75.127.82 "source /etc/profile;/root/denocn.sh"
