name: CI

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: denolib/setup-deno@v1
        with:
          deno-version: "v0.38.0"
      - name: build web
        run: |
          ./build.sh
      - name: Build Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS registry.cn-hongkong.aliyuncs.com
          docker build ./ -t registry.cn-hongkong.aliyuncs.com/denocn/denocn-website
          docker push registry.cn-hongkong.aliyuncs.com/denocn/denocn-website

  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: ${{ secrets.DEPLOY_SCRIPT }}
